export {default as Home} from './Home/Home'
export {default as Search} from './Search/Search'
export {default as Details} from './Details/Details'
export {default as Cart} from './Cart/Cart'
export {default as Checkout} from './Checkout'